server:
  port: 8005
spring:
  application:
    name: admin-server
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: xxx@qq.com
          to: ndong211@163.com
# http://codecentric.github.io/spring-boot-admin/1.5.6/#mail-notifications
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://slc11fsp.us.oracle.com:8000}/eureka/

management.security.enabled: false

