server:
  port: 8101
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lovemooner/spring-cloud-examples/     # 配置git仓库的地址
          search-paths: config-repo                                     # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: lovemooner                                          # git仓库的账号
          password: ccx3801=                                            # git仓库的密码
          force-pull: true
#  rabbitmq:
#    host: slc11fsp.us.oracle.com
#    port: 5672
#    username: admin
#    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://slc11fsp.us.oracle.com:8000/eureka/   ## 注册中心eurka地址


#management:
#  security:
#     enabled: false

